apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: luis-rivas-be
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
    - port: 80
      targetPort: 8090
      nodePort: 30090
