apiVersion: v1
kind: Secret
metadata:
  name: student-secret
  namespace: luis-rivas-be
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://ep-super-mode-ahbe7kpv.c-3.us-east-1.aws.neon.tech/studentdb?sslmode=require
  DB_USERNAME: neondb_owner
  DB_PASSWORD: npg_4LXUo5scMpKH
  APP_PORT: "8090"
